### ISSUE TITLE
Qtcreator 4.9.1 Based on Qt 5.12.3 

### ISSUE THREAD

**Issue by marriusco** [jontio/qt_esp8266_wizard#1]
Failed to parse "/home/marius/APPS/QTCREATOR/Tools/QtCreator/share/qtcreator/templates/wizards/projects/esp8266/wizard.json":146:6: unterminated object
There is an open bracket there.

**Comment by jontio** [comment]
Not that I can see. I'm not sure why it's disliking that line...
```
					"source": "project.creator",
```

**Comment by circinusX1** [comment]
I had an open bracket there. Could be the file transfer or such. Is fixed. You can close the issue. Thank you.
Same reported different account.
